replicaCount: 2

image:
  repository: rest-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  port: "3000"
  openWeatherApiKey: "test-key"
  exchangeApi: "https://open.er-api.com/v6/latest/USD"

db:
  host: mydb-postgresql
  port: "5432"
  name: appdb
  user: appuser
  password: apppassword

probes:
  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 10
  livenessInitialDelaySeconds: 15
  livenessPeriodSeconds: 20
