apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: rest-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.env.port | quote }}
            - name: OPENWEATHER_API_KEY
              value: {{ .Values.env.openWeatherApiKey | quote }}
            - name: EXCHANGE_API
              value: {{ .Values.env.exchangeApi | quote }}
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              value: {{ .Values.db.user | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
